### ISSUE TITLE
Not Working on 1.19.4

### ISSUE THREAD

**Issue by capturedbytenph** [WMGameLive/AutoFishing#1]
I just added this to my papermc server and not sure why isn't working. I also added this to LuckPerms but the only things I get is reload.
![image](https://user-images.githubusercontent.com/16754847/226946474-fb904914-b515-472b-901a-a7e21014024c.png)
Not sure if I missed something

Thanks,

**Comment by WMGameLive** [comment]
Still not support 1.19.4, I will update it next few days.

**Comment by capturedbytenph** [comment]
Nice! Thanks!
